export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const ADJUST_QTY = "ADJUST_QTY";
export const ADD_PRODUCTS = "ADD_PRODUCTS";